### PR TITLE
LSB tarnslations

### PR DESCRIPTION
**Pull request by LearningSandbox-garethb**
Added new language JSONs to locales for multiple assets: "DNA to protein", "Exploring hydrophobic core" and "Protein folding".
Languages include: ar (Arabic), it (Italian), nl (Dutch), de (German), pt (Portuguese), tr (Turkish), fr (French), ko (Korean), zh (Simplified Chinese), js (Japanese) and es (Spanish).

(Translation.json in lab repo not yet updated)
Please inform us of any queries or errors.

### CODE REVIEW

**Comment by dstrawberrygirl** [comment]
Thanks for this PR, this adds a lot of useful translations. I tested out the code and discovered it did not display icons for some of these languages, so I did some investigation. 

Flags for languages are always problematic, and we can't solve this quite so easily (Spanish is spoken in Spain, Mexico, Argentina, to mention just a tiny number of Spanish-speaking countries) but this oversimplification is the current system in use in Lab so I guess we can start from there for now. We do have several existing flags we can use from the Lab repository if you can make a couple of adjustments to these translations to match the two letter international code:

- Japanese: JP
- Korean: KR is the country code for South Korea, KP for North Korea, and we have flags for both of these countries.
- Simplified Chinese: the code is correct, but there is no one flag we can use for this. We need an icon to represent the language, so a suggestion I've seen in a few places is to use  简 to represent Simplified Chinese and 繁 to represent Traditional Chinese. This requires changes in the other PR (https://github.com/concord-consortium/lab/pull/156) I will add notes describing what is needed.

**Comment by dstrawberrygirl** [comment]
I will also note here that the Arabic text seems to be correct, but does not seem to display aligned right-to-left. I am not a native Arabic speaker so I will attempt to get more feedback on this and determine if this is acceptable as a first-pass translation.

**Comment by LearningSandbox-garethb** [comment]
Good day.

Thank you for the feedback. We will address the language codes and the
Simplified Chinese flag points and make the requests sometime this week. We
will await further feedback concerning the Arabic, but we suggest that come
in a separate pull request from the above changes.

Thanks again.

**Comment by LearningSandbox-garethb** [comment]
Good day.

Our branch has been updated with the language code changes in order to
match the flag codes.
The Simplified Chinese (zh) flag has been added is will reflex it the
respective repo/branch very soon.
Let us know of any updates and queries.

Kind regards.

**Comment by dstrawberrygirl** [comment]
Looks good, thanks!

**Pull request merged**
