### PR TITLE
Dissociation energy version 2

### PR DESCRIPTION
**Pull request by bhavna19nagpal**
The newer version has
1) KE on by default in the beginning
2) Bonded atoms in the beginning
3) dissociation-slider getting disabled on play.

### CODE REVIEW

**Comment by ddamelin** [comment]
This was a good start. I would recommend two changes.
- Change the title of this to  "Making and Breaking Bonds: The Affect of Temperature" so it can be distinguished from the original.
- Remove the Dissociation slider. You can use the setBondEnergy API call in the onLoad section of the interactive to set an initial value without the need for the dissociationEnergy parameter and slider.

If you do future additional work it would be helpful to make a branch in your fork that is somewhat descriptive of the work contained in the pull request. Typically, when working on interactives some branch name related to that interactive.

**Comment by rklancer** [comment]
"The _Effect_ of Temperature", please.

With regards, 
your friendly local grammar cop

**Comment by ddamelin** [comment]
Thank you!

**Comment by rklancer** [comment]
You're welcome! Just saw "the affect of temperature" in my inbox and thought, "hmm." Although the warmer temperatures lately have had the effect of affecting my affective state. :)

**Pull request closed without merging**
