### PR TITLE
boiling-point-polar-nonpolar

### PR DESCRIPTION
**Pull request by rishiloyola**

### CODE REVIEW

**Comment by ddamelin** [comment]
Sorry I was not more specific earlier, but the location of the interactive JSON should be in src/interactives/interactions/

The "interactions" project is the one these interactives are being used in.

Consequently, the model JSON files would best be placed in:
models/lab-version/1/md2d/interactions/boiling-point-polar-nonpolar/

The converted-models directory is sort of a left over from when we initially converted a large number of mml files. From this point forward it probably makes sense to use the models directory instead.

**Comment by ddamelin** [comment]
Looks like there is a problem with this build. See the "details" link above where it says there is an error.

**Comment by rishiloyola** [comment]
Sorry,I was pushing wrong boiling-point-polar-nonpolar.json file.
Now, you can test it.

**Comment by rishiloyola** [comment]
You can close this pull request to avoid confusion.

**Pull request closed without merging**
