### PR TITLE
Add Docker support for containerizing web application.

### PR DESCRIPTION
**Pull request by ghyde**
This adds support for creating a sandboxed environment specifically for lab-interactives-site. This will allow people to skip the environment setup and go straight into developing/extending the web application.

### CODE REVIEW

**Comment by knowuh** [comment]
Thanks for the PR @ghyde  – Looks good to me. :+1:  attn: @scytacki

**Comment by scytacki** [comment]
Thanks @ghyde, hopefully this will help others get setup faster. 

Do you have plans to deploy the lab interactives site locally?

We occasionally update the Lab Framework used by the interactives site, before doing so we'll make a release here: https://github.com/concord-consortium/lab/releases.  If you want to stay up-to-date you might want to follow that repository.

**Comment by ddamelin** [comment]
Just so folks are aware, Garrett made these interactives for Rebecca Sansom, former SAM project member, who linked up with us through Chad at NSF while she was the Albert Einstein Distinguished Educator Fellow. Now she is a professor in the Chemistry and Biochemistry department at Brigham Young University. I helped set them up to develop their own interactives, which they were hosting locally, but Rebecca offered to contribute them back to our collection. 

I'm not sure if they plan to continue to host remotely as well or not.

**Comment by ghyde** [comment]
@scytacki, I currently have a couple of interactives that my department developed and are hosting locally. However, as @ddamelin mentioned, I would like to merge them into your collection.

This PR was simply the work I did to get my dev environment created. Hopefully it'll help others, too. I'll create another PR for the interactives later.

**Pull request merged**
