### PR TITLE
mixing-liquids

### PR DESCRIPTION
**Pull request by rishiloyola**

### CODE REVIEW

**Comment by rishiloyola** [comment]
Why this interactive failed to build? Locally it is working fine and doesn't giving me any error. Help me to fix this error.

**Comment by ddamelin** [comment]
I believe you need to remove the $ from the model names. For example "particleMixing$0.json" should be renamed to "particleMixing.json"

**Comment by rishiloyola** [comment]
You can test this interactive.
Url - http://lab.concord.org/branch/mixing-liquids/interactives.html#interactives/interactions/Mixing-polar-nonpolar-particle.json

**Comment by ddamelin** [comment]
Thanks for the link. Normally we put links for testing in Pivotal Tracker. That way you can deliver and provide the link for viewing.

**Comment by rishiloyola** [comment]
I don't know why this failed ? Help me to fix this.

**Pull request merged**
